name: CI Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build changed projects
        run: dotnet build

      - name: Build unit tests projects
        run: |
            cd /mySolarPower.Tests
            dotnet build mySolarPower.Tests.csproj
            
      - name: Run unit tests projects
        run: dotnet test

