name: my-solar-power
on: push
jobs: 
  my-solar-power-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with: 
          repository: |
            angelllopez/mySolarPower
          path: |
            mySolarPower/MySolarPower.Data/MySolarPower.Data.csproj
            mySolarPower/mySolarPower.API/MySolarPower.API.csproj
            mySolarPower/mySolarPower.Services/MySolarPower.Services.csproj
            mySolarPower/mySolarPower.Tests/MySolarPower.Tests.csproj            
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --no-restore --verbosity normal --framework net7.0
