name: my-solar-power
on: push
jobs: 
  my-solar-power-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Build and test solution
        run: |
          dotnet restore
          dotnet build
          dotnet test
          working-directory: ./mySolarPower

